name: cron job demo

on:
  schedule:
    - cron: '20 12 * * *'
    - cron: '30 12 * * *'
    - cron: '40 12 * * *'
    - cron: '50 12 * * *'


jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
