name: cron job demo

on:
  schedule:
    - cron: '20 * * * *'
    - cron: '30 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
