name: GitHub Actions Demo

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: self-hosted
    steps:
      - run: ../../cukinia ../../cukinia.conf.sample
