name: GitHub Actions Demo

on:
  pull_request:
    types: [opened, reopened, edited]
jobs:
  approved:
    runs-on: self-hosted
    steps:
      - run: /home/eroussy/tmp/actions-runner/cukinia /home/eroussy/tmp/actions-runner/cukinia.conf.sample
