name: GitHub Actions Demo

env:
  PR_N: $(echo $GITHUB_REF | cut -d '/' -f 3)
  TIME: $(date +%Hh%Mm%S)
  CI_DIR: /tmp/seapath-ci-${{ env.GITHUB_REF }}

on: [push]

jobs:
  approved:
    runs-on: self-hosted
    steps:
      - name: Give link
        run: echo $CI_DIR
