name: GitHub Actions Demo

on: [push]

jobs:
  approved:
    runs-on: self-hosted
    steps:
      - name: Download ci
        run: export CI_DIR=/tmp/seapath-ci-${RANDOM};
             mkdir $CI_DIR; cd $CI_DIR;
             git clone --depth 1 -b main https://github.com/seapath/ci ci
      - name: Run ci
        run: echo bip boup
      - name: Give link
        run: echo $CI_DIR
