name: GitHub Actions Demo

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    runs-on: self-hosted
    steps:
      - run: /home/eroussy/tmp/actions-runner/cukinia /home/eroussy/tmp/actions-runner/cukinia.conf.sample
